window.SPEC = {
  "title": "Devin Security Swarm",
  "subtitle": "Find real exploits, prove them, and fix them",
  "outro": "Found, proven, and fixed",
  "speed": 3,
  "cps": 48,
  "voOutro": "Security Swarm. Real exploits, found, proven, and fixed.",
  "edit": {
    "0000.png": { "hold": 2.6, "cursor": false, "vo": "This is Devin Security Swarm. It reads your code like an attacker, proves each bug is real, and fixes it." },
    "0002.png": { "vo": "First, create a scan profile." },
    "0009.png": { "vo": "Give it a name." },
    "0016.png": { "vo": "Turn on sandbox validation, so Devin runs your app and tries every exploit." },
    "0018.png": { "vo": "Tell it how to start the app, and who the test users are." },
    "0020.png": { "hold": 2.6 },
    "0021.png": { "vo": "Then create the profile." },
    "0024.png": { "skip": true },
    "0025.png": { "hold": 0.8 },
    "0026.png": { "vo": "Now start a scan." },
    "0028.png": { "vo": "Set it up manually," },
    "0030.png": { "vo": "pick a single repo," },
    "0031.png": { "cap": "Pick the repository" },
    "0040.png": { "vo": "and choose the profile." },
    "0044.png": { "vo": "Turn on Interactive mode, so you review the threat model before it scans." },
    "0047.png": { "vo": "Then run the scan." },
    "0049.png": { "hold": 0.6, "badge": "Sped up", "cap": "The scan starts with a threat model" },
    "0050.png": { "skip": true }, "0051.png": { "hold": 0.5 }, "0052.png": { "skip": true },
    "0053.png": { "hold": 0.5 }, "0054.png": { "skip": true }, "0055.png": { "skip": true },
    "0056.png": { "hold": 2.4, "badge": null, "cursor": false, "vo": "Devin studies the code and proposes a scan model: what an attacker could reach, the trust boundaries, and the entry points." },
    "0057.png": { "vo": "It already suspects the X-Forwarded-User header," },
    "0058.png": { "vo": "records fetched by ID with no owner check," },
    "0059.png": { "vo": "and file paths built from user input." },
    "0060.png": { "vo": "You can give feedback, or approve it." },
    "0064.png": { "hold": 0.6 },
    "0065.png": { "hold": 1.6, "badge": "Sped up", "cap": "Findings arrive, grouped by severity", "vo": "Findings stream in, grouped by severity." },
    "0070.png": { "hold": 0.6 }, "0075.png": { "hold": 0.6 },
    "0080.png": { "hold": 2.2, "cap": "Then Devin tries every exploit in a sandbox", "vo": "Then Devin tries to exploit each one in a sandbox." },
    "0085.png": { "hold": 0.6 }, "0090.png": { "hold": 0.6 },
    "0066.png": { "skip": true },
    "0067.png": { "skip": true },
    "0068.png": { "skip": true },
    "0069.png": { "skip": true },
    "0071.png": { "skip": true },
    "0072.png": { "skip": true },
    "0073.png": { "skip": true },
    "0074.png": { "skip": true },
    "0076.png": { "skip": true },
    "0077.png": { "skip": true },
    "0078.png": { "skip": true },
    "0079.png": { "skip": true },
    "0081.png": { "skip": true },
    "0082.png": { "skip": true },
    "0083.png": { "skip": true },
    "0084.png": { "skip": true },
    "0086.png": { "skip": true },
    "0087.png": { "skip": true },
    "0088.png": { "skip": true },
    "0089.png": { "skip": true },
    "0091.png": { "skip": true },
    "0092.png": { "skip": true },
    "0093.png": { "skip": true },
    "0094.png": { "skip": true },
    "0095.png": { "hold": 3.0, "badge": null, "cap": "7 open, 5 dismissed as duplicates or false positives", "vo": "Duplicates and false positives are dismissed. Seven findings are open, and two are chained across files." },
    "0096.png": { "skip": true }, "0097.png": { "skip": true }, "0098.png": { "skip": true }, "0099.png": { "skip": true },
    "0100.png": { "skip": true }, "0101.png": { "skip": true }, "0102.png": { "skip": true }, "0103.png": { "skip": true },
    "0104.png": { "vo": "Open the worst one." },
    "0106.png": { "hold": 2.8, "cursor": false, "vo": "It's critical, with high confidence. Anyone can become an admin, with no password." },
    "0107.png": { "vo": "Here's the attack path, step by step." },
    "0108.png": { "vo": "And the exact lines, across four files." },
    "0109.png": { "vo": "Devin ran the exploit in a sandbox, and it worked. Confirmed." },
    "0110.png": { "vo": "This is the real request that proved it." },
    "0111.png": { "vo": "Now assign it to Devin." },
    "0113.png": { "hold": 1.2 },
    "0114.png": { "vo": "A fix session starts right away." },
    "0116.png": { "hold": 2.8, "cursor": false, "capPos": "bottom", "vo": "Devin takes the finding and its evidence, fixes the code, and adds tests for the forged header." },
    "0117.png": { "hold": 0.8, "capPos": "bottom" }, "0118.png": { "hold": 1.0, "capPos": "bottom" }, "0119.png": { "hold": 0.8, "capPos": "bottom" },
    "0120.png": { "hold": 2.4, "capPos": "bottom", "vo": "Then it opens a pull request." },
    "0121.png": { "skip": true },
    "0122.png": { "hold": 1.2, "vo": "Back on the finding, the fix PR is attached." },
    "0123.png": { "hold": 1.6 },
    "0124.png": { "hold": 3.2, "cursor": false, "vo": "A real exploit chain, found, proven, and fixed." },
    "0125.png": { "skip": true }
  }
};
