window.SPEC = {
  "title": "Devin Security Swarm",
  "subtitle": "Find real exploits, prove them, and fix them",
  "outro": "Found, proven, and fixed",
  "speed": 3,
  "cps": 48,
  "voOutro": "Security Swarm. Real exploits, found, proven, and fixed.",
  "edit": {
    "0000.png": { "skip": true },
    "0001.png": { "hold": 2.6, "cursor": false, "vo": "This is Devin Security Swarm. It reads your code like an attacker, proves each bug is real, and fixes it." },
    "0002.png": { "vo": "First, let Devin write a scan profile for your repo." },
    "0005.png": { "hold": 0.8 },
    "0006.png": { "hold": 3.4, "capPos": "bottom", "vo": "Devin opens a session, looks at your repos, and asks which one the profile is for." },
    "0009.png": { "hold": 3.6, "capPos": "bottom", "cap": "Devin drafts the profile and lists the optional settings", "vo": "It drafts what to look for and how to validate it, then lists a few optional settings." },
    "0010.png": { "vo": "Accept the defaults and add one triage rule: any auth bypass or cross-user leak is always critical." },
    "0044.png": { "hold": 2.4, "capPos": "bottom" },
    "0045.png": { "vo": "Devin shows the change as a diff, and you approve it." },
    "0047.png": { "hold": 1.6, "capPos": "bottom", "cap": "The profile is ready" },
    "0048.png": { "skip": true },
    "0049.png": { "vo": "Now open the profile it created." },
    "0051.png": { "skip": true },
    "0053.png": { "hold": 4.2, "vo": "The scan model tells the scanner what to hunt for: auth bypass, access between users, and file paths, with the exact files to check." },
    "0054.png": { "hold": 3.4, "vo": "Triage guidance decides how findings are ranked, so our rule makes these always critical." },
    "0055.png": { "hold": 4.0, "vo": "Sandbox validation tells Devin how to start the API, which test users to log in as, and to prove every finding with curl." },
    "0056.png": { "hold": 2.4, "cap": "Report: an optional summary when the scan finishes", "vo": "A summary report is optional, and this profile leaves it off." },
    "0057.png": { "skip": true },
    "0060.png": { "hold": 3.6, "vo": "Under Advanced, it skips tests and seed scripts, and validates every finding from medium up." },
    "0061.png": { "skip": true },
    "0062.png": { "hold": 0.8 },
    "0063.png": { "vo": "Now start a scan, set it up manually on a single repo, and choose the new profile." },
    "0081.png": { "vo": "Turn on Interactive mode, so you review the threat model before it scans." },
    "0084.png": { "vo": "Then run the scan." },
    "0086.png": { "hold": 1.2, "cap": "The scan starts with a threat model" },
    "0087.png": { "skip": true }, "0088.png": { "skip": true }, "0089.png": { "skip": true }, "0090.png": { "skip": true },
    "0091.png": { "cam": { "x": 885, "y": 405, "z": 1.3 }, "camDur": 0.01, "hold": 3.0, "vo": "Before it scans, Devin proposes a scan model of rules written for this exact code." },
    "0092.png": { "vo": "It already suspects the forwarded user header, boards loaded by ID with no owner check, and file paths built from user input." },
    "0095.png": { "hold": 1.4 },
    "0096.png": { "vo": "This looks right, so start scanning." },
    "0098.png": { "skip": true },
    "0099.png": { "cam": "reset", "camDur": 0.01, "hold": 1.4 },
    "0100.png": { "hold": 0.8, "speed": 40, "badge": "Sped up", "cap": "Findings arrive, grouped by severity" },
    "0115.png": { "hold": 1.6, "vo": "Findings stream in, grouped by severity." },
    "0124.png": { "hold": 2.0, "cap": "Then Devin tries every exploit in a sandbox", "vo": "Then Devin tries to exploit each one in a sandbox." },
    "0125.png": { "speed": 100 },
    "0145.png": { "hold": 3.0, "speed": 3, "badge": null, "cap": "11 open, 8 dismissed as duplicates or false positives", "vo": "Duplicates and false positives are dismissed, which leaves eleven open findings, and three of them are chained across files." },
    "0146.png": { "skip": true }, "0147.png": { "skip": true }, "0148.png": { "skip": true }, "0149.png": { "skip": true },
    "0150.png": { "hold": 1.6 },
    "0151.png": { "vo": "Open the worst one." },
    "0153.png": { "hold": 3.0, "cursor": false, "vo": "It's critical, with high confidence, because anyone who sends one header becomes the admin, with no password." },
    "0154.png": { "vo": "Here's the attack path, step by step." },
    "0155.png": { "cap": "The exact lines in auth.js", "vo": "And here are the exact lines in auth.js that make it possible." },
    "0156.png": { "vo": "Devin ran the exploit in a sandbox, and it worked, so the finding is confirmed." },
    "0157.png": { "cap": "The real requests that proved it", "vo": "These are the real requests that proved it." },
    "0158.png": { "vo": "Now assign it to Devin." },
    "0160.png": { "hold": 1.2 },
    "0161.png": { "vo": "A fix session starts right away, so open it." },
    "0163.png": { "skip": true },
    "0164.png": { "hold": 3.2, "cursor": false, "capPos": "bottom", "vo": "Devin gets the finding and its evidence, and checks that the bug is still real on main." },
    "0165.png": { "hold": 4.6, "capPos": "bottom", "cap": "It reuses an open fix PR and reruns the tests", "vo": "An open pull request from an earlier run already fixes it, so Devin takes it over, reruns the tests, and checks that the header alone is now rejected." },
    "0166.png": { "hold": 0.8, "capPos": "bottom" },
    "0167.png": { "hold": 2.4, "capPos": "bottom", "cap": "Only the real proxy, with a shared secret, can set the user" },
    "0168.png": { "skip": true },
    "0169.png": { "hold": 1.2, "vo": "Back on the finding, the fix PR is attached." },
    "0170.png": { "hold": 2.0 },
    "0171.png": { "hold": 3.6, "cursor": false, "cap": "Only the real proxy, with a shared secret, can set the user", "vo": "A real exploit chain, found, proven, and fixed." },
    "0172.png": { "skip": true },
    "0173.png": { "skip": true }
  }
};
