import { Rec, sleep } from '../_kit/capture/rec.mjs';
import { testAndMerge } from '../_kit/capture/testmerge.mjs';
import { showModels, showEnvironments, mentionRepo, editorBox, clearComposer, ensureAgent } from '../_kit/capture/composer.mjs';

const ORG = process.env.DEVIN_ORG_URL || 'https://app.devin.ai/org/thequantexplorer';
const SESSION_TITLE = process.env.SESSION_TITLE || 'Add root .prettierrc config';
const r = await new Rec('shots').init();
const p = r.p;
const hov = async (t, meta = {}) => { const b = await r.move(t); await r.shot({ kind: 'hover', target: b, ...meta }); };
const nav = label => ({ text: label, sel: 'span', exact: true });

await r.goto(ORG, 3500);
for (let i = 0; i < 60 && !(await p.evaluate(t => [...document.querySelectorAll('a')].some(a => a.innerText.includes(t)), SESSION_TITLE)); i++) await sleep(500);
await sleep(800);
await clearComposer(p); await sleep(400);
await ensureAgent(r);
await p.mouse.move(720, 620);
r.cur = { x: 720, y: 620 };
await r.shot({ hold: 1.6, cap: 'Devin is an autonomous AI software engineer' });
await hov('main [contenteditable=true]', { cap: 'Describe a task in plain English', hold: 1.4 });
await r.point({ text: 'Ask', sel: 'main button', exact: true }, { hold: 1.2, cap: 'Ask to explore and plan · Agent to build and ship' });
await r.point({ text: 'Agent', sel: 'main button', exact: true }, { hold: 0.8 });
await r.click({ text: SESSION_TITLE, sel: 'span, div, a' }, { pre: { cap: 'Every session is a conversation plus Devin\'s own workspace' }, wait: 4000 });
await p.evaluate(() => { [...document.querySelectorAll('main button, main [role=tab]')].filter(x => x.innerText.trim() === 'Computer' && x.getBoundingClientRect().y < 40).forEach(x => x.querySelector('button[aria-label="Close tab"]')?.click()); });
await sleep(800);
{ const pr0 = await p.evaluate(() => { const e = [...document.querySelectorAll('main button, main [role=tab]')].find(x => x.innerText.trim() === 'Progress' && x.getBoundingClientRect().x > 760 && x.getBoundingClientRect().y < 40); if (!e) return null; const b = e.getBoundingClientRect(); return { x: b.x + b.width / 2, y: b.y + b.height / 2 }; }); if (pr0) { await p.mouse.click(pr0.x, pr0.y); await sleep(1500); } }
await r.move({ x: 560, y: 520 });
await r.shot({ hold: 2.4 });
const tabPos = label => p.evaluate(l => { const e = [...document.querySelectorAll('main button, main [role=tab]')].find(x => x.innerText.trim() === l && x.getBoundingClientRect().x > 760 && x.getBoundingClientRect().y < 40); if (!e) return null; const b = e.getBoundingClientRect(); return { x: b.x + b.width / 2, y: b.y + b.height / 2 }; }, label);
const prog = await tabPos('Progress');
if (prog) { await p.mouse.click(prog.x, prog.y); await sleep(1500); }
const add = await p.evaluate(() => { const e = document.querySelector('main button[aria-label="Add tab"]'); const b = e.getBoundingClientRect(); return { x: b.x + b.width / 2, y: b.y + b.height / 2 }; });
await r.click(add, { pre: { cap: 'Devin has its own computer, with a browser, shell, and editor' }, wait: 1200 });
const item = await p.evaluate(() => { const e = [...document.querySelectorAll('[role=menuitem]')].find(x => x.innerText.trim() === 'Computer'); if (!e) return null; const b = e.getBoundingClientRect(); return { x: b.x + b.width / 2, y: b.y + b.height / 2 }; });
if (!item) throw new Error('no Computer menu item');
await r.click(item, { wait: 6000 });
await r.move({ x: 560, y: 520 });
await sleep(1500);
const live = await p.evaluate(() => [...document.querySelectorAll('main button, main span')].some(e => e.innerText.trim() === 'Live' && e.getBoundingClientRect().x > 760));
if (!live) throw new Error('Computer tab not live');
await r.shot({ hold: 2.2, cap: 'Here it runs the app it is building in its own browser' });
const prt = await p.evaluate(() => { const e = [...document.querySelectorAll('main button, main [role=tab]')].find(x => /^PR #\d+$/.test(x.innerText.trim()) && x.getBoundingClientRect().x > 760 && x.getBoundingClientRect().y < 40); if (!e) return null; const b = e.getBoundingClientRect(); return { x: b.x + b.width / 2, y: b.y + b.height / 2 }; });
if (!prt) throw new Error('no PR tab');
await r.click(prt, { pre: { cap: 'Review every change Devin made in its PR' }, wait: 3500 });
await r.shot({ hold: 1.6 });
await r.click(nav('Review'), { pre: { cap: 'Review pull requests with Devin Review' }, wait: 3500 });
await r.shot({ hold: 1.8 });
await r.click(nav('Wiki'), { pre: { cap: 'Wiki keeps living docs for your repos' }, wait: 9000 });
await r.shot({ hold: 1.8 });
await r.click(nav('Automations'), { pre: { cap: 'Automations run Devin on a schedule or trigger' }, wait: 3500 });
await r.shot({ hold: 1.8 });
await r.click(nav('Customize'), { pre: { cap: 'Customize with knowledge, playbooks, and MCPs' }, wait: 3500 });
await r.shot({ hold: 1.8 });
await r.click(nav('New session'), { pre: { cap: 'Start a new session' }, wait: 3000 });
await clearComposer(p); await sleep(400);
await ensureAgent(r);
await r.shot({ hold: 1.0 });
await showModels(r, { cap: 'Choose a model for the job' });
await showEnvironments(r);
await r.click(await editorBox(p), { pre: { cap: 'Give it a clear task and say what done looks like' }, wait: 300 });
await mentionRepo(r, process.env.REPO_QUERY || 'repos:product', process.env.REPO || 'product-demo-apps');
await r.type(process.env.TASK || ' in the kanban-board app, add a progress bar to the board header that shows what share of cards are done.', { every: 5 });
await sleep(500);
await r.shot({ hold: 1.4 });
await r.shot({ hold: 0.5 });
await p.keyboard.press('Enter');
await sleep(2500);
r.mark('sent', { cap: 'Press Enter and Devin gets to work' });
console.log('SESSION', await p.evaluate(() => location.href));
await testAndMerge(r, { mergedCap: 'Merged. Clear task in, pull request out' });
r.done();
console.log('beats', r.beats.length);
