window.SPEC = {
  "title": "Devin Automations: events",
  "subtitle": "CI fails, Devin fixes it on its own",
  "outro": "Let events start the work",
  "speed": 3,
  "cps": 48,
  "noZoom": [["0053.png", "0073.png"]],
  "voOutro": "Set up an event trigger once, and Devin picks up the work whenever it happens.",
  "edit": {
    "0000.png": { "waitVo": true },
    "i0013.png": { "waitVo": true },
    "i0001.png": { "vo": "Automations let Devin start work without anyone prompting it, and there are a few ways they can run." },
    "i0002.png": { },
    "i0007.png": { "vo": "They can fire on events, like a new message in a Slack channel or a failing GitHub check, or they can run on a schedule." },
    "i0008.png": { "voSync": 3.7, "hold": 1.4 },
    "i0009.png": { "voSync": 5.4 },
    "i0010.png": { "hold": 1.6, "voGap": 1.2, "vo": "The sessions they start can use your MCP integrations, like Datadog, Sentry, Notion, or any other MCP server you connect." },
    "i0011.png": { "cap": "Sentry works too", "voSync": 3.8, "hold": 0.4 },
    "i0012.png": { "cap": "Notion too, and any MCP you connect", "hold": 1.6, "voSync": 4.2 },
    "i0016.png": { "voGap": 1.2, "vo": "You can also create an automation in natural language. Just describe what you want, and Devin drafts it for you to review." },
    "i0017.png": { "voSync": 2.8 },
    "0001.png": { "cap": "Now build one step by step", "voGap": 1.4, "vo": "Now let's build one step by step, and watch it fire." },
    "0002.png": { "vo": "Create a new automation and give it a name." },
    "0006.png": { },
    "0013.png": { "vo": "For the trigger, pick GitHub, then Check run, which fires whenever CI reports a result." },
    "0016.png": { "voSync": 1.7 },
    "0018.png": { "vo": "Choose the private repo to watch, and add a condition so it only fires when the check fails.", "voDelay": 1.5 },
    "0022.png": { "voSync": 1.9 },
    "0033.png": { "vo": "Each failure starts a new Devin session with these instructions." },
    "0034.png": { },
    "0038.png": { "vo": "Cap how much each session can spend, and how often the automation can run." },
    "0042.png": { "voSync": 2.4 },
    "0046.png": { "vo": "Save it, and it waits for CI to fail." },
    "0053.png": { "hold": 2.8, "cap": "A new PR shows issues left in the header", "cam": { "x": 640, "y": 790, "z": 1.5 }, "camForce": true, "camDur": 1.0, "voGap": 1.2, "vo": "This new pull request shows how many issues are left, but it also has a type error." },
    "0054.png": { "skip": true },
    "0055.png": { "cam": "reset", "camForce": true, "camDur": 0.8, "vo": "Open the pull request, and CI runs on it, but the check fails.", "voDelay": 3.0 },
    "0059.png": { "voSync": 1.2 },
    "0060.png": { "cam": { "x": 612, "y": 620, "z": 1.4 }, "camForce": true, "camDur": 0.8, "cap": "The check fails", "voSync": 2.4 },
    "0061.png": { "cam": "reset", "camForce": true, "camDur": 0.6, "vo": "The automation sees the failure and starts this session on its own, with no one prompting it." },
    "0062.png": { "voSync": 1.5 },
    "0063.png": { "capPos": "bottom" },
    "0065.png": { "capPos": "bottom", "vo": "Devin looks at why CI failed, finds the type error, and pushes a one-line fix to the same branch." },
    "0071.png": { "capPos": "bottom", "voSync": 3.2 },
    "0072.png": { "vo": "The fix passed, the check is green, and the new header shows how many issues are left.", "hold": 1.4 },
    "0073.png": { "cam": { "x": 1250, "y": 300, "z": 1.6 }, "camForce": true, "camDur": 1.0, "voSync": 2.0 }
  }
};
