window.SPEC = {
  "title": "Devin Automations: events",
  "subtitle": "CI fails, Devin fixes it on its own",
  "outro": "Let events start the work",
  "speed": 3,
  "cps": 48,
  "pollRunMax": 2.5,
  "noZoom": [["0075.png"]],
  "voOutro": "Set up a trigger once, and Devin picks up the work whenever it happens.",
  "edit": {
    "0000.png": { "hold": 0.8 },
    "0001.png": { "hold": 2.6, "capPos": "bottom", "cap": "Automations start Devin sessions for you", "vo": "Automations let Devin start work without anyone prompting it. You define a trigger once, and Devin handles each event as it arrives." },
    "0004.png": { "cap": "Templates show what they can do", "waitVo": true },
    "0006.png": { "hold": 1.0, "cap": null, "vo": "An automation can run on an event, like a message in a Slack channel or a failing GitHub check, or on a schedule." },
    "0007.png": { "ring": true, "ringFor": 1.8, "cap": "A Slack message", "voSync": 2.6 },
    "0008.png": { "ring": true, "ringFor": 1.8, "cap": "A GitHub event", "voSync": 4.4 },
    "0009.png": { "ring": true, "ringFor": 1.8, "cap": "Or a schedule", "voSync": 5.6 },
    "0010.png": { "ring": true, "ringFor": 1.6, "cap": "Datadog for logs and metrics", "voGap": 0.8, "vo": "The sessions it starts can use your MCP integrations, like Datadog, Sentry, and Notion, to pull in logs, errors, and docs." },
    "0011.png": { "ring": true, "ringFor": 1.6, "cap": "Sentry for errors", "voSync": 2.6 },
    "0012.png": { "ring": true, "ringFor": 1.8, "cap": "Notion, or any MCP you connect", "voSync": 3.6 },
    "0013.png": { "cap": null, "waitVo": true },
    "0015.png": { "cap": "Or generate one with Devin", "vo": "You can also describe an automation in plain English, and Devin builds it with you." },
    "0018.png": { "ring": true, "ringFor": 2.4, "cap": "Describe it, and Devin drafts it", "hold": 1.6 },
    "0020.png": { "cap": null, "waitVo": true },
    "0021.png": { "cap": "Now build one by hand", "voGap": 0.8, "vo": "Now let's build one by hand, and watch it fire." },
    "0025.png": { "cap": null, "vo": "Create a new automation and give it a name." },
    "0031.png": { "hold": 0.8 },
    "0032.png": { "cap": "GitHub, then Check run", "vo": "For the trigger, pick GitHub, then Check run, which fires whenever CI reports a result." },
    "0036.png": { "hold": 0.8 },
    "0037.png": { "cap": "The private repo to watch", "vo": "Choose the private repo to watch." },
    "0041.png": { "cap": "Add a condition", "vo": "Then add a condition, so it only fires when the check's conclusion is failure." },
    "0046.png": { "vo": "Now it ignores passing checks and only runs when one fails." },
    "0051.png": { "ring": true, "ringFor": 2.2, "cap": "Only when the check fails", "hold": 0.9 },
    "0052.png": { "ring": true, "ringFor": 2.4, "cap": "Each failure starts a new session", "vo": "Each failure starts a new Devin session, with the event's details added to its prompt." },
    "0053.png": { "cap": "What Devin should do", "vo": "The instructions tell Devin to read the logs, fix the root cause, and push to the same branch." },
    "0055.png": { "ring": true, "ringFor": 2.4, "hold": 2.6 },
    "0056.png": { "cap": "Spend and rate limits", "vo": "Limits cap what each session can spend, and how often the automation can run." },
    "0063.png": { "ring": true, "ringFor": 2.4, "cap": "$10 per session, 5 runs an hour", "hold": 1.6 },
    "0064.png": { "cap": null, "vo": "Create it, and it waits for CI to fail." },
    "0067.png": { "capPos": "bottom", "cap": "Active, with no events yet", "hold": 1.4 },
    "0069.png": { "ring": { "x": 487, "y": 545, "w": 780, "h": 112 }, "ringFor": 3.2, "target": { "x": 487, "y": 545, "w": 780, "h": 112 }, "cap": "A string where a number belongs", "hold": 3.4, "voGap": 0.8, "vo": "This pull request adds an issues left count to the header, but it passes a string where the function expects a number." },
    "0070.png": { "cap": null, "vo": "CI runs on it, and the check fails." },
    "0071.png": { "ring": true, "ringFor": 2.2, "cap": "The check fails", "hold": 2.4 },
    "0072.png": { "ring": true, "ringFor": 2.6, "cap": "The automation fired", "hold": 2.8, "vo": "The automation sees the failure and starts a session on its own, with no one prompting Devin." },
    "0075.png": { "ring": { "x": 747, "y": 337, "w": 830, "h": 290 }, "ringFor": 3.0, "capPos": "top", "cap": "The check run that triggered it is in the prompt", "hold": 2.6, "vo": "The session starts with the check run that triggered it. Devin reads the logs, finds the type error, and pushes a fix to the same branch." },
    "0100.png": { "ring": { "x": 747, "y": 445, "w": 840, "h": 160 }, "ringFor": 3.2, "cap": "Fixed on the same branch", "hold": 3.4, "vo": "Then it reports the root cause and the one-line fix." },
    "0101.png": { "ring": true, "ringFor": 2.6, "capPos": "bottom", "cap": "A second commit, and the check is green", "hold": 3.2, "vo": "Back on the pull request, Devin's commit is on the branch, and the check is green." }
  }
};
