window.SPEC = {
  "title": "Devin in Slack",
  "subtitle": "Ask questions and run sessions from any channel",
  "outro": "Work with Devin in Slack",
  "speed": 3,
  "cps": 14,
  "capPos": "bottom",
  "capArrows": false,
  "noZoom": [["0000.png", "0051.png"]],
  "voOutro": "That's Devin in Slack.",
  "edit": {
    "0000.png": { "hold": 2.6, "vo": "Once Devin is in a Slack channel, you can tag it from any message." },
    "0003.png": { "vo": "Type at-Devin," },
    "0004.png": { "capPos": "top", "vo": "and start with bang-ask to get a quick answer about your code, without starting a full session." },
    "0009.png": { "skip": true }, "0010.png": { "skip": true }, "0011.png": { "skip": true }, "0012.png": { "skip": true },
    "0013.png": { "skip": true }, "0014.png": { "skip": true }, "0015.png": { "skip": true }, "0016.png": { "skip": true },
    "0017.png": { "skip": true },
    "0008.png": { "hold": 0.8, "badge": "Sped up" },
    "0018.png": { "hold": 0.8, "badge": "Sped up" },
    "0019.png": { "badge": "", "vo": "The answer comes back in a thread, with links to the code it read." },
    "0020.png": { "hold": 1.2 }, "0021.png": { "hold": 1.2 },
    "0026.png": { "capPos": "top", "vo": "For real work, tag Devin with a task. Bang-fast runs it in Fast mode." },
    "0027.png": { "hold": 1.6, "vo": "That starts a full Devin session." },
    "0030.png": { "hold": 0.8, "badge": "Sped up" },
    "0031.png": { "badge": "", "vo": "Devin does the work and replies in the thread." },
    "0034.png": { "capPos": "top", "vo": "Reply in the thread to keep going. You don't need to tag it again." },
    "0035.png": { "skip": true },
    "0036.png": { "hold": 0.8, "badge": "Sped up" },
    "0037.png": { "badge": "", "cap": "Devin answers the follow-up", "vo": "It picks up right where it left off." },
    "0038.png": { "vo": "The same session is in the Devin web app, so you can follow along there too." },
    "0041.png": { "capPos": "top", "vo": "When you're done, type archive to close out the session." },
    "0042.png": { "skip": true }, "0043.png": { "skip": true }, "0044.png": { "skip": true }, "0046.png": { "skip": true },
    "0047.png": { "skip": true }, "0048.png": { "skip": true }, "0049.png": { "skip": true }, "0050.png": { "skip": true },
    "0045.png": { "hold": 0.8 },
    "0051.png": { "hold": 2.0, "cap": "Devin archives the session" }
  }
};
