window.SPEC = {
  "title": "Devin in Slack",
  "subtitle": "Ask questions and run sessions from any channel",
  "outro": "Work with Devin in Slack",
  "speed": 3,
  "cps": 48,
  "capPos": "auto",
  "capArrows": false,
  "pollRunMax": 3,
  "voOutro": "That's Devin in Slack.",
  "edit": {
    "0000.png": { "hold": 2.6, "cursor": false, "vo": "Once Devin is in a Slack channel, you can tag it from any message." },
    "0003.png": { "cap": "Type @Devin" },
    "0006.png": { "target": {"x": 370, "y": 650, "w": 525, "h": 40}, "hl": true, "cap": "Pick Devin from the list", "vo": "Type at Devin, and pick it from the list." },
    "0007.png": { "target": {"x": 761.2, "y": 701.2, "w": 1297.5, "h": 147.5}, "hl": true, "cap": "!ask gets a quick answer, without a full session", "vo": "Start with bang-ask to get a quick answer about your code, without starting a full session." },
    "0008.png": { "hl": true },
    "0009.png": { "cap": "Open the thread" },
    "0011.png": { "badge": "Sped up" },
    "0028.png": { "target": {"x": 1233.1, "y": 311.2, "w": 393.8, "h": 125}, "hl": true, "badge": "", "cap": "The answer, with links to the code it read", "vo": "The answer comes back in a thread, with links to the code it read." },
    "0029.png": { "hold": 1.2 },
    "0030.png": { "skip": true }, "0031.png": { "hold": 1.2 }, "0032.png": { "skip": true }, "0033.png": { "hold": 1.2 }, "0034.png": { "hold": 1.2 },
    "0035.png": { "target": {"x": 761.2, "y": 701.2, "w": 1297.5, "h": 147.5}, "cap": "For real work, tag Devin with a task" },
    "0037.png": { "target": {"x": 761.2, "y": 701.2, "w": 1297.5, "h": 147.5}, "hl": true, "cap": "!fast starts a full session in Fast mode", "vo": "For real work, tag Devin with a task. Bang-fast runs it as a full Devin session, in Fast mode." },
    "0038.png": { "hl": true },
    "0039.png": { "cap": "A few minutes later, Devin replies", "vo": "A few minutes later, Devin replies in the thread." },
    "0041.png": { "skip": true }, "0042.png": { "skip": true }, "0043.png": { "skip": true },
    "0044.png": { "target": {"x": 1233.1, "y": 363.8, "w": 393.8, "h": 432.5}, "hl": true, "cap": "Devin did the work and replied with the total", "vo": "It did the work, and the total is right there." },
    "0045.png": { "vo": "Reply in the thread to keep going. You don't need to tag it again." },
    "0047.png": { "target": {"x": 1233.1, "y": 685, "w": 363.8, "h": 180}, "hl": true, "cap": "A plain reply, no tag needed" },
    "0049.png": { "badge": "Sped up" },
    "0054.png": { "target": {"x": 1233.1, "y": 473.8, "w": 393.8, "h": 212.5}, "hl": true, "badge": "", "cap": "Devin answers the follow-up", "vo": "It picks up right where it left off." },
    "0055.png": { "hl": true, "cap": "Open the same session in the web app", "vo": "Click the link to open the same session in the Devin web app." },
    "0056.png": { "hold": 0.8 },
    "0057.png": { "target": {"x": 780, "y": 86.2, "w": 745, "h": 117.5}, "hl": true, "cap": "The session Slack started, with the whole thread", "vo": "The whole thread is here too, so you can follow along in the browser." },
    "0058.png": { "vo": "When you're done, type archive to close out the session." },
    "0064.png": { "target": {"x": 1233.1, "y": 685, "w": 363.8, "h": 180}, "hl": true, "cap": "Type archive" },
    "0067.png": { "target": {"x": 1133.1, "y": 555, "w": 53.7, "h": 30}, "hl": true, "hold": 2.6, "cap": "Devin archives the session", "vo": "Devin reacts with a box, and the session is archived." }
  }
};
