window.SPEC = {
  "title": "DeepWiki",
  "subtitle": "Living documentation for every repository",
  "outro": "Read the code like a book",
  "speed": 3,
  "cps": 48,
  "noZoom": [["0024.png"]],
  "voOutro": "Read your code like a book.",
  "edit": {
    "0000.png": { "hold": 2.6, "cursor": false,
      "vo": "This is DeepWiki. Devin indexes every repository you connect, and writes a wiki for it automatically.",
      "voSay": "This, is Deep Wiki. Devin indexes every repository you connect, and writes a wiki for it automatically." },
    "0001.png": { "vo": "Open Wiki from the sidebar." },
    "0002.png": { "hold": 1.6, "vo": "Each connected repo has its own wiki, and you can generate one for any repo that doesn't have one yet." },
    "0003.png": { "vo": "Pick a repository to read its wiki." },
    "0004.png": { "hold": 2.0, "vo": "It opens on an overview of the whole codebase." },
    "0005.png": { "cam": { "x": 760, "y": 220, "z": 1.6 }, "camDur": 1.0, "vo": "Every page lists the source files it was built from." },
    "0006.png": { "hold": 1.8 },
    "0007.png": { "cam": "reset", "camDur": 0.8 },
    "0009.png": { "cam": { "x": 920, "y": 300, "z": 1.35 }, "camDur": 1.0, "vo": "Architecture diagrams are generated for you." },
    "0010.png": { "vo": "Expand one to see the full picture." },
    "0011.png": { "hold": 2.4 },
    "0012.png": { "cam": "reset", "camDur": 0.8, "vo": "The sidebar has a page for each part of the codebase." },
    "0014.png": { "hold": 1.8 },
    "0015.png": { "vo": "And every claim links to the exact source lines it comes from." },
    "0021.png": { "cam": { "x": 1200, "y": 170, "z": 1.6 }, "camDur": 1.0,
      "vo": "From this menu, you can re-index the wiki, edit it, or open DeepWiki settings.",
      "voSay": "From this menu, you can re-index the wiki, edit it, or open Deep Wiki settings." },
    "0023.png": { "hold": 2.2, "vo": "To steer which pages get written, add a .devin/wiki.json file to the repo.",
      "voSay": "To steer which pages get written, add a dot devin slash wiki dot json file to the repo." },
    "0024.png": { "cam": { "x": 860, "y": 560, "z": 1.4 }, "camDur": 1.0, "vo": "You can also ask Devin about the repo, right from the wiki." },
    "0041.png": { "hold": 0.8 },
    "0042.png": { "cam": "reset", "camDur": 0.8, "hold": 1.4, "vo": "Devin uses the wiki to find the right context, then searches your code." },
    "0047.png": { "vo": "It reads the files it needs, and writes up the answer." },
    "0061.png": { "hold": 3.0, "vo": "The answer cites the files and lines it came from, and opens them right next to it." }
  }
};
