window.SPEC = {
  "title": "DeepWiki",
  "subtitle": "Living documentation for every repository",
  "outro": "Read the code like a book",
  "speed": 3,
  "cps": 30,
  "capPos": "auto",
  "capArrows": false,
  "pollRunMax": 2.5,
  "edit": {
    "0000.png": { "hold": 2.4, "cursor": false, "vo": "DeepWiki turns every repository you connect into a wiki that Devin writes from the code, and keeps up to date." },
    "0001.png": { "cap": "Open the sidebar", "ring": true, "vo": "Open the sidebar, and click Wiki." },
    "0003.png": { "cap": "Click Wiki", "ring": true },
    "0004.png": { "hold": 1.6, "cap": "Every connected repo gets a wiki", "capPos": "top", "vo": "Every repo you connect gets its own wiki." },
    "0005.png": { "cap": "Search for a repo", "ring": true, "vo": "Search for a repo, and open its wiki." },
    "0011.png": { "cap": "Open its wiki", "capPos": "bottom", "ring": true },
    "0012.png": { "hold": 2.2, "cap": "Pages Devin wrote from the code", "capPos": "bottom", "vo": "Devin writes these pages from the code itself, and organizes them by topic." },
    "0013.png": { "cap": "Relevant source files", "ring": true, "vo": "Every page lists the source files it was built from." },
    "0015.png": { "hold": 1.8, "cap": "The files this page was built from", "ring": true },
    "0016.png": { "hold": 1.6, "cap": "Generated architecture diagrams", "ring": true, "vo": "Architecture diagrams are generated for you, and you can expand them to look closer." },
    "0017.png": { "cap": "Expand the diagram", "ring": true },
    "0018.png": { "hold": 2.0, "cap": "" },
    "0019.png": { "cap": "The wiki's pages are in the sidebar", "ring": true, "vo": "The sidebar becomes a table of contents for the whole wiki." },
    "0021.png": { "cap": "Open another page", "ring": true, "vo": "Open another page, like this one on the kanban board app." },
    "0022.png": { "hold": 2.0, "cap": "" },
    "0023.png": { "cap": "More actions", "ring": true, "vo": "From this menu, you can re-index the wiki, edit it, or open DeepWiki settings." },
    "0025.png": { "hold": 2.2, "cap": "Re-index, edit, or open DeepWiki settings", "ring": true },
    "0026.png": { "cap": "Ask Devin about this repo", "ring": true, "vo": "You can also ask Devin about the repo, right from the wiki." },
    "0028.png": { "hold": 1.4, "cap": "Ask a question", "ring": true },
    "0029.png": { "cap": "Send it" },
    "0031.png": { "badge": "Sped up", "hold": 0.6, "cap": "", "vo": "Devin searches the code to answer." },
    "0053.png": { "badge": "", "hold": 2.6, "cap": "Answers cite the files and lines they came from", "ring": { "x": 1015, "y": 332, "w": 827, "h": 198 }, "vo": "The answer cites the files and lines it came from, and shows that code right next to it." },
    "0054.png": { "ring": true, "vo": "Click any citation to jump to those lines." },
    "0056.png": { "hold": 3.0, "cap": "The cited lines, highlighted", "ring": true }
  }
};
