window.SPEC = {
  "title": "Devin Memory",
  "subtitle": "Devin remembers how you like to work",
  "outro": "Devin remembers how you work",
  "speed": 3,
  "cps": 48,
  "capPos": "auto",
  "capArrows": false,
  "pollRunMax": 2,
  "noZoom": [["0046.png", "0049.png"], ["0098.png", "0104.png"]],
  "voOutro": "Memory is built on Agent Memory Repo, an open spec you can use in your own agents too.",
  "edit": {
    "0048.png": { "hold": 0.5 },
    "0051.png": { "hold": 0.5 },
    "0053.png": { "hold": 0.5 },
    "0055.png": { "hold": 0.5 },
    "0062.png": { "hold": 0.5 },
    "0099.png": { "skip": true },
    "0100.png": { "skip": true },
    "0101.png": { "skip": true },
    "0102.png": { "skip": true },
    "0000.png": { "hold": 2.6, "cursor": false, "vo": "This is Devin Memory. Devin remembers what it learns from working with you, across every session." },
    "0001.png": { "cap": "Tell Devin how you like to work", "vo": "Say you have a preference, like how you want status updates." },
    "0003.png": { "cursor": false, "cam": { "x": 720, "y": 362, "z": 1.3 }, "camDur": 1.0 },
    "0028.png": { "cursor": true, "cam": "reset", "camDur": 0.8, "hold": 1.4, "hl": true, "cap": "Ask Devin to remember it", "vo": "You can tell Devin to remember it." },
    "0029.png": { "cap": null },
    "0046.png": { "hold": 3.0, "hl": true, "cap": "Devin saves memories on its own, no approval needed", "vo": "But Devin also saves and edits memories on its own as you work, with no approval step. Each time it does, an Updated memory card shows up in the session." },
    "0047.png": { "cap": "Open the memory card" },
    "0049.png": { "hold": 3.0, "hl": true, "cap": "Memories are Markdown notes in a Git repo", "vo": "Your memories are Markdown notes in a Git repo, called your memory drive." },
    "0050.png": { "cap": "Open Customize, then Memory", "vo": "You can browse them anytime in Customize, Memory." },
    "0054.png": { "cap": "Open MEMORY.md" },
    "0056.png": { "hold": 2.6, "hl": true, "cap": "MEMORY.md: preferences and an index", "vo": "MEMORY.md holds your general preferences, and an index of your other notes." },
    "0057.png": { "cap": "View the source" },
    "0058.png": { "hold": 0.5 },
    "0059.png": { "hold": 3.2, "hl": true, "cap": "Each entry links back to its session", "vo": "Each entry is one line, with a link back to the session where Devin learned it." },
    "0060.png": { "hold": 3.2, "hl": true, "cap": "Dreaming tidies memory about once a day", "vo": "About once a day, Dreaming reviews your recent sessions. It merges duplicates, drops stale notes, and adds lessons it missed." },
    "0061.png": { "cap": "Open More actions" },
    "0063.png": { "hold": 2.6, "hl": true, "cap": "Personal to you, and easy to turn off", "vo": "Memory is personal to you, and you can turn it off here anytime." },
    "0064.png": { "skip": true },
    "0065.png": { "hold": 1.6, "cursor": false, "cap": null, "vo": "New memories apply to future sessions." },
    "0066.png": { "cursor": true, "cap": "Start a new session" },
    "0068.png": { "vo": "So in a new session, ask for a status update.", "cursor": false, "cam": { "x": 720, "y": 362, "z": 1.3 }, "camDur": 1.0 },
    "0096.png": { "cursor": true, "cam": "reset", "camDur": 0.8, "hold": 0.6, "hl": true },
    "0097.png": { "cap": null },
    "0103.png": { "vo": "Devin already follows your preference: three short bullets, and no emojis." },
    "0104.png": { "hold": 3.4, "cursor": false, "hl": true, "cap": "Three short bullets, no emojis" }
  }
};
