window.SPEC = {
  "title": "Devin Memory",
  "subtitle": "Devin remembers how you like to work",
  "outro": "Devin remembers how you work",
  "speed": 3,
  "cps": 48,
  "capPos": "bottom",
  "capArrows": false,
  "noZoom": [["0031.png", "0036.png"], ["0047.png", "0079.png"]],
  "voOutro": "Memory is built on Agent Memory Repo, an open spec you can use in your own agents too.",
  "edit": {
    "0000.png": { "hold": 2.6, "cursor": false, "vo": "This is Devin Memory. Devin remembers what it learns from working with you, across every session." },
    "0001.png": { "cap": "Tell Devin how you like to work", "vo": "Say you have a preference, like how you want status updates." },
    "0003.png": { "cursor": false, "cam": { "x": 720, "y": 330, "z": 1.3 }, "camDur": 1.0 },
    "0030.png": { "cursor": true, "cam": "reset", "camDur": 0.8, "cap": "Ask Devin to remember it", "vo": "You can tell Devin to remember it." },
    "0031.png": { "hold": 2.6, "cap": "Devin saves memories on its own, no approval needed", "vo": "But Devin also saves and edits memories on its own as you work, with no approval step. Each time it does, an Updated memory card shows up in the session." },
    "0032.png": { "skip": true },
    "0033.png": { "hold": 0.6 },
    "0035.png": { "hold": 3.0, "cursor": false, "cap": "Memories are Markdown notes in a Git repo", "vo": "Your memories are Markdown notes in a Git repo, called your memory drive." },
    "0036.png": { "skip": true },
    "0037.png": { "hold": 2.4, "cap": "Browse them in Customize, Memory", "vo": "You can browse them anytime in Customize, Memory." },
    "0038.png": { "hold": 2.0, "cap": "MEMORY.md: preferences and an index", "vo": "MEMORY.md holds your general preferences, and an index of your other notes." },
    "0039.png": { "cap": "View the source" },
    "0041.png": { "hold": 3.2, "cam": { "x": 880, "y": 560, "z": 1.3 }, "camDur": 1.0, "cap": "Each entry links back to its session", "vo": "Each entry is one line, with a link back to the session where Devin learned it." },
    "0042.png": { "hold": 3.2, "cam": "reset", "camDur": 0.8, "cap": "Dreaming tidies memory about once a day", "vo": "About once a day, Dreaming reviews your recent sessions. It merges duplicates, drops stale notes, and adds lessons it missed." },
    "0043.png": { "hold": 0.6 },
    "0045.png": { "hold": 2.6, "cap": "Personal to you, and easy to turn off", "vo": "Memory is personal to you, and you can turn it off here anytime." },
    "0046.png": { "skip": true },
    "0047.png": { "hold": 1.6, "cursor": false, "vo": "New memories apply to future sessions." },
    "0048.png": { "cap": "Start a new session", "vo": "So in a new session, ask for a status update." },
    "0050.png": { "cursor": false },
    "0078.png": { "cursor": true },
    "0079.png": { "hold": 3.4, "cursor": false, "cap": "Three short bullets, no emojis", "vo": "Devin already follows your preference: three short bullets, and no emojis." }
  }
};
